In [1]:
import requests
a = requests.get('https://money.cnn.com/data/dow30/')

In [27]:
pattern = re.compile('class="wsod_symbol">(.*?)<\/a>&nbsp;<span.*?>(.*?)<\/span>.*?\n.*?class="wsod_stream">(.*?)<\/span><\/td>')

In [28]:
import re
s = re.findall(pattern , a.text)

In [31]:
import pandas as pd
output = pd.DataFrame(s)

In [32]:
output.columns = ['code','name','value']

In [34]:
output.index = [i+1 for i in range(len(output))]

In [35]:
output

    code                     name   value
1    MMM                       3M  218.51
2    AXP         American Express  113.85
3   AAPL                    Apple  203.90
4     BA                   Boeing  380.72
5    CAT              Caterpillar  143.77
6    CVX                  Chevron  119.28
7   CSCO                    Cisco   56.31
8     KO                Coca-Cola   47.44
9    DIS                   Disney  131.80
10   DOW             Dow Chemical   57.99
11   XOM              Exxon Mobil   81.25
12    GS            Goldman Sachs  206.95
13    HD               Home Depot  206.26
14   IBM                      IBM  140.02
15  INTC                    Intel   58.58
16   JNJ        Johnson & Johnson  137.45
17   JPM           JPMorgan Chase  114.86
18   MCD               McDonald's  192.73
19   MRK                    Merck   72.51
20  MSFT                Microsoft  122.19
21   NKE                     Nike   89.18
22   PFE                   Pfizer   38.88
23    PG         Procter & Gamble  106.04
24   TRV  Travelers Companies Inc  139.79
25   UTX      United Technologies  136.51
26   UNH             UnitedHealth  218.54
27    VZ                  Verizon   57.83
28     V                     Visa  159.75
29   WMT                 Wal-Mart  103.14
30   WBA                 Walgreen   55.17